language: objective-c
osx_image: xcode8.3
before_install:
   - brew update
   - brew outdated carthage || brew upgrade carthage
before_script:
  - cd GossipGeek
  - carthage bootstrap --platform ios

script: xcodebuild test -scheme GossipGeek -destination 'platform=iOS Simulator,name=iPhone 6'

 notifications:
  slack:
    rooms:
      - gg201708:9VilroUBvf9aFX7AfK9h6Q8d#travis