language: objective-c
osx_image: xcode8.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - cd GossipGeek
  - carthage update
script: xcodebuild test -scheme GossipGeek -destination 'platform=iOS Simulator,name=iPhone 6'
